version: "3.8"

services:
  db:
    image: postgres
    container_name: reddit-postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=seeing-science
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: reddit-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - ./data/pgadmin:/root/.pgadmin
    ports:
      - "8000:80"
